### ISSUE TITLE
Animated driver.js does not work on fixed bootstrap 4 navbar example

### ISSUE THREAD

**Issue by 00cpxxx** [kamranahmedse/driver.js#95] opened 2018-05-06 22:59 UTC
This bug is a continuation of issue #31. This is a copy & paste from the bootstrap navbar sample with some highlight steps added to it. I understand that it is probably related to some css wizardry used by bootstrap to make the navbar stays fixed. Tested in Chrome 65 and Firefox 51.

First step output (targeting the navbar as a whole):
![image](https://user-images.githubusercontent.com/8762620/39678704-ac4ffe3a-5167-11e8-979b-c722f10a758a.png)

Second step output displying blank box over the menu (targeting a menu item). Menu text is black so this should not be the issue.
![image](https://user-images.githubusercontent.com/8762620/39678712-cb99ebe8-5167-11e8-9d58-562e120d05aa.png)

To test on plunker it is required to resize the output screen to avoid the menu collapse by bootstrap.
https://plnkr.co/edit/K2FWX6Wn096kFXy9F6Qy?p=preview

Alternatively this is a direct link to the same file that can be opened in a standard browser window.
https://alexa.pro.br/driver/teste.html

**Comment by BrandonSchreck** [comment] 2018-07-26 14:00
I have the same issue with bootstrap v3.3.5 .navbar-fixed-top, .navbar-fixed-bottom css class. If changed from fixed to absolute the element is highlighted correctly. However, this causes the navbar to scroll with the page instead of being a fixed element.

**Comment by kamranahmedse** [comment] 2018-09-29 11:07
Duplicate of https://github.com/kamranahmedse/driver.js/issues/112

**Closed by kamranahmedse** 2018-09-29 11:07 UTC

**Comment by law-chain-hot** [comment] 2020-02-14 16:15
> I have the same issue with bootstrap v3.3.5 .navbar-fixed-top, .navbar-fixed-bottom css class. If changed from fixed to absolute the element is highlighted correctly. However, this causes the navbar to scroll with the page instead of being a fixed element.

Hi, did you solve the problem?

**Comment by jsivelopment** [comment] 2021-05-26 16:28
Any solution on this?
