### ISSUE TITLE
Popovers are cut off at bottom and right border of screen

### ISSUE THREAD

**Issue by anselmpaul** [kamranahmedse/driver.js#17] opened 2018-03-14 09:00 UTC
Both with `position: 'auto'` or `position: 'left' / 'top'.`
![screen shot 2018-03-14 at 09 54 18](https://user-images.githubusercontent.com/22657579/37392450-7fae10ec-276e-11e8-8f03-f8da19168c3c.png)
![screen shot 2018-03-14 at 09 56 33](https://user-images.githubusercontent.com/22657579/37392453-82e4035c-276e-11e8-8ddb-0d93805fec8e.png)

**Comment by kamranahmedse** [comment] 2018-03-14 09:30
Thank you for reporting. Will look into it. Closing it as the duplicate of #18

**Closed by kamranahmedse** 2018-03-14 09:30 UTC
