### ISSUE TITLE
Improve popover 'position'

### ISSUE THREAD

**Issue by marlenesco** [kamranahmedse/driver.js#89] opened 2018-04-27 16:16 UTC
![screen shot 2018-04-27 at 17 49 15](https://user-images.githubusercontent.com/445087/39371930-5c9b2dae-4a43-11e8-97fd-89f70da9ebcc.png)

Hi, the popover position, when we have a fullscreen element, is not properly displayed (take a look at the screenshot).

It should have popover position options for X and Y axis:

```
const driver = new Driver();
driver.highlight({
  element: '#some-element',
  popover: {
    title: 'Title for the Popover',
    description: 'Description for it',
    position: ['center', 'top'], // X axis can be `left`, `center`, `right`
                                 // Y axis can be `top`, `center`, `bottom`
  }
});
```

BTW, thank you for this awesome repo.
David

**Comment by kamranahmedse** [comment] 2018-04-27 18:13
Thank you and yes I am aware of it and it is on the priority list. Closing this for being the duplicate of https://github.com/kamranahmedse/driver.js/issues/18

**Closed by kamranahmedse** 2018-04-27 18:13 UTC
