### ISSUE TITLE
No functionality in IE11

### ISSUE THREAD

**Issue by lb13** [kamranahmedse/driver.js#9] opened 2018-03-12 16:22 UTC
Hi there, although the README says that this works with IE, I'm experiencing issues with IE11, which unfortunately I need to support for a current project.

None of the pop-ups or overlaps display when opening in IE11, and your demo site also does not function either. Other than that, it's a really awesome project, and it works well in modern browsers!

I've found a limited workaround, which is documented here: https://stackoverflow.com/questions/35215360/getting-error-object-doesnt-support-property-or-method-assign#39021339

This has restored some functionality - the boxes appear where they should, and they cycle through in the correct order, but there is no framing of the highlighted element - just reduced opacity background across the whole page. It works, but doesn't look as nice.

Equally, there is no animation, although this is less of an issue.

**Comment by kamranahmedse** [comment] 2018-03-12 21:25
Hey, unfortunately, I don't have internet explorer to test this; will try to do it on the VM soon. Thank you for reporting though.

**Comment by jstnbr** [comment] 2018-03-13 21:32
Demo site not working on Safari 9.1.2.

Safari 9.1.2 was released about 1.5 years ago. I would think it's still a modern browser.

**Comment by kamranahmedse** [comment] 2018-03-14 00:08
The rewrite has been completed.

@lb13 could you please test and see if it works now, if not could you please have a look at the console and paste any errors here.

@jstnbr also could you please test now?

**Comment by jstnbr** [comment] 2018-03-14 01:41
Demo is working on Safari 9.1.2 now.

**Comment by lb13** [comment] 2018-03-14 08:11
Many thanks for the latest update - this definitely works better - elements are highlighted and transitions have smoother animations. There are no errors being reported in the console. The workaround I linked in my original post is still required, but that's down to IE being IE.

However, there is a minor issue in how the highlighting works across all browsers (tested in Chrome, Firefox, and IE). Whereas previously the element was shown and the background dimmed, some elements are now 'whited out' and do not show their contents. In this case, the popover is mapped to an anchor inside a list item in the format:

```html
<li>
  <a class="mapToThis">Support</a>
  <div class="hiddenDropDown">
  -- extra content --
  </div>
</li>
```

Changing the mapped element to the ```<li>``` does not change this behaviour. 

![image](https://user-images.githubusercontent.com/25256821/37389863-d532db12-275d-11e8-9f75-a59d27791a55.png)

Overall it definitely looks better, but it would be handy if the highlighting didn't wash out the element it was attached to.

**Comment by kamranahmedse** [comment] 2018-03-14 08:19
Seems to be some sort of z-index issue. Could you possibly create a reproducing plunkr with your HTML/CSS of this item?

**Comment by lb13** [comment] 2018-03-14 16:02
Here's a reproduction of the issue: http://plnkr.co/06MPCAHfQlle8ObgRITT

As best I can tell, the background overlay is applying an opacity filter across the entire page, and then the #driver-highlighted-element-stage tag is setting the background of each highlighted element to white to compensate / contrast, but interestingly this does not cause problems when the element is the entire navbar.

I was able to workaround this in the linked plunkr by adding an additional line of CSS that specified the background colour for the highlighted element, but obviously this makes the highlighter useless for anything with a different coloured background.

```css
#driver-highlighted-element-stage {
  background-color: #8bc2f2!important;
}
```

I tried setting the fix to ```inherit!important``` but that didn't seem to work.

**Comment by kamranahmedse** [comment] 2018-03-14 17:20
Aha, thanks for getting back with the details.

Well in that case, it seems to be working fine. At this moment we are not identifying the color of the element before adding the "stage" below it. So if text color is white it will definitely get hidden on top of the stage. One way you can resolve this is to give your anchors the background color of the navbar (it won't affect the design because it already has the nav of same background below it) so that when the stage comes below the element, element already has its background color and will be visible.

```css
li a.mapToThis { 
    background-color: $nav-color;
}
```
Hope you got the idea. I am going to close this issue, since the original IE functionality issue has been resolved. If you have any questions, do let me know.

**Closed by kamranahmedse** 2018-03-14 17:20 UTC
Labels: awaiting-response

**Comment by lb13** [comment] 2018-03-15 08:44
That did the trick! Many thanks for your support :)
