### ISSUE TITLE
Fixed position element targets are not handled correctly

### ISSUE THREAD

**Issue by grandynguyen** [kamranahmedse/driver.js#97] opened 2018-05-08 16:51 UTC
Overlay and popover elements should have fixed positioning if the highlighted element has it's position fixed.

**Comment by SGoldenGraham** [comment] 2018-05-12 14:51
I have a codepen example of this not working:
[Fixed position Codepen](https://codepen.io/SGoldenGraham/project/editor/AJGGKy)

**Comment by BrandonSchreck** [comment] 2018-07-26 13:59
I have the same issue with bootstrap v3.3.5 .navbar-fixed-top, .navbar-fixed-bottom css class. If changed from fixed to absolute the element is highlighted correctly. However, this causes the navbar to scroll with the page instead of being a fixed element.

**Comment by kamranahmedse** [comment] 2018-09-29 11:07
Duplicate of https://github.com/kamranahmedse/driver.js/issues/112

**Closed by kamranahmedse** 2018-09-29 11:07 UTC

**Comment by jsivelopment** [comment] 2021-05-26 16:26
Any solution of this issue?

**Comment by AndyLiHong** [comment] 2021-07-15 07:46
Any solution of this issue?
