### ISSUE TITLE
In-page scrolling doesn't make driver update

### ISSUE THREAD

**Issue by ineentho** [kamranahmedse/driver.js#75] opened 2018-04-16 16:23 UTC
Example: https://jsfiddle.net/oLj3ksr3/4/

I'm not sure how hard it would be to detect these scroll events, but it would be great if driver.js could handle this case.

**Comment by kamranahmedse** [comment] 2018-06-30 10:55
Duplicate of https://github.com/kamranahmedse/driver.js/issues/112

**Closed by kamranahmedse** 2018-06-30 10:55 UTC
