### ISSUE TITLE
[BUG] Responsive popover

### ISSUE THREAD

**Issue by Rombecchi** [kamranahmedse/driver.js#68] opened 2018-04-10 21:59 UTC
When go responsive and "position" is set in popover, it will should override that position with one "more responsive" like "bottom" or "top"

![cattura1](https://user-images.githubusercontent.com/1488340/38585741-40a0d728-3d1b-11e8-9b4c-fab2697723ce.JPG)

**Comment by kamranahmedse** [comment] 2018-04-11 22:59
Duplicate of https://github.com/kamranahmedse/driver.js/issues/18

**Closed by kamranahmedse** 2018-04-11 22:59 UTC

**Comment by Naren-hybreeder** [comment] 2022-03-18 15:13
@kamranahmedse I think this is a common issue in all mobile devices. I have tried the below code and it's working on desktop but getting issues in the mobile devices. Popover showing on the right side in the mobile along with the horizontal scroll.

```
popover: {
     className: 'tour',
      title: 'sometext here',
      position: 'right'
    }
<link rel="stylesheet" href="https://unpkg.com/driver.js/dist/driver.min.css">
<script src="https://unpkg.com/driver.js/dist/driver.min.js"></script>
```
![Screenshot 2022-03-18 at 8 42 08 PM](https://user-images.githubusercontent.com/16729825/159029626-4eb821f6-13ea-4f80-b0f9-d4d115f24f31.png)
