### ISSUE TITLE
Element is not highlighted when there are more than one element with same class

### ISSUE THREAD

**Issue by parmii** [kamranahmedse/driver.js#135] opened 2018-10-23 10:20 UTC
If there are more than one element with same class name, then first element with that class should be highlighted with pop up. I have tried with so many options such as element: 'div[class="x"]' | element: '.x' | element:'.x:first' but none of these is working.

**Comment by Attrash-Islam** [comment] 2019-01-12 22:08
You can do `document.querySelectorAll(".my-class")[0]`.

**Comment by kamranahmedse** [comment] 2019-02-07 21:44
@parmii I tried it and it seems to be working fine when there is same class on multiple elements. Could you check your console and see if there is any error? Plus we will be able to help you better if you provide a reproducing plunkr/fiddle/codesandbox link.

Closing it for now, please re-open with the details so that we may help.

**Closed by kamranahmedse** 2019-02-07 21:44 UTC
