### ISSUE TITLE
Popover outside of window bounds

### ISSUE THREAD

**Issue by timothyallan** [kamranahmedse/driver.js#84] opened 2018-04-26 05:41 UTC
Great project!
What I've not been able to find is if there's a way to prevent the popover from going outside the document/window bounds? I don't have a position manually set, and assumed the libarary would pick the best position for display, however my popovers constantly go out of window bounds.

![screen shot 2018-04-25 at 11 36 51 pm](https://user-images.githubusercontent.com/1995135/39287656-ff3dc048-48e1-11e8-858d-bd71929931b0.png)

**Comment by kamranahmedse** [comment] 2018-04-26 06:54
Duplicate of https://github.com/kamranahmedse/driver.js/issues/18. Currently, it handles the popups cutting off from top or bottom. I need to improve the positioning; will do as soon as I can. Thanks

**Closed by kamranahmedse** 2018-04-26 06:54 UTC
